// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using trainee.Models;

#nullable disable

namespace trainee.Migrations
{
    [DbContext(typeof(TraineeContext))]
    [Migration("20231222110439_trainee")]
    partial class trainee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("trainee.Models.traineeModel", b =>
                {
                    b.Property<string>("Employeeid")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("EmployeeDesignation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeFathername")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("EmployeeSalary")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Employeeid");

                    b.ToTable("trainee");
                });
#pragma warning restore 612, 618
        }
    }
}
